[package]
name = "lovem"
version = "0.0.17"
edition = "2021"
authors = ["kratenko"]

[dependencies]
clap = { version = "3.2", features = ["derive"] }
anyhow = "1.0"
lazy_static = "1.4"
regex = "1.6"
parse_int = "0.6.0"
moveslice = "2.0"
