# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Lovem
site_url: https://kratenko.github.io/lovem
site_author: kratenko
theme:
  name: material
  language: en
  custom_dir: overrides
  features:
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.expand

use_directory_urls: false

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - exclude:
      glob:
        - drafts/*
  - gen-files:
      scripts:
        - blogem.py
  - literate-nav:
      nav_file: NAV.md
      implicit_index: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: kratenko
      repo: lovem
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - The Journey: index.md
  - Journal: journal/
  - Journal (complete months): months/
#  - Entries:
#    - 2022-06/making-virtual-a-reality.md
#    - 2022-06/what-is-a-virtual-machine-anyway.md
#    - 2022-06/script-or-virtual.md
#    - 2022-06/that-use-case.md
#    - 2022-06/we-need-another-wheel.md
#    - 2022-06/lovem-again.md
